StockMarketSite/StockMarketSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('StockMarketApp.urls')),
    path('stockquotes/', include('stockquotes.urls')),
    path('stocknews/', include('stocknews.urls')),
    path('admin/', admin.site.urls),
]

StockMarketSite/stocknews/urls.py
from django.urls import path
from . import views

app_name = 'stocknews'


urlpatterns = [
    path('news_home/', views.news_home, name="news_home"),
]

StockMarketSite/stockquotes/urls.py
from django.urls import path
from . import views


app_name = 'stockquotes'

urlpatterns = [
    path('qhome/', views.qhome, name="qhome"),
    path('add_stock.html', views.add_stock, name="add_stock"),
    path('delete/<stock_id>', views.delete, name="delete"),
]

StockMarketSite/stockquotes/models.py
from django.db import models
from django.contrib.auth.models import User
class Stock(models.Model) :
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ticker = models.CharField(max_length=10)

    def __str__(self):
        return self.ticker
# Create your models here.

StockMarketSite/stockquotes/forms.py
from django import forms
from .models import Stock

class StockForm(forms.ModelForm) :
    class Meta :
        model = Stock
        fields = ["ticker"]

StockMarketSite/stockquotes/views.py
from django.shortcuts import render, redirect
from .models import Stock
from .forms import StockForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required


def qhome ( request ) :

    ticker_symbol = "NASDAQ:NDX"  # Default ticker symbol

    if request.method == 'POST' :
        ticker = request.POST['ticker']  # 'ticker' is the one in the qhome.html <input> name
        ticker_symbol = ticker

    return render(request, 'stockquotes/qhome.html', {'ticker_symbol' : ticker_symbol})

    # import requests
    # import json
    #
    # processed_api = {}  # Initialize as an empty dictionary
    # ticker_symbol = "AAPL"
    #
    #
    # if request.method == 'POST' :
    #     ticker = request.POST['ticker']  # 'ticker' is the one in the qhome.html <input> name
    #     # apikey: AD3P4POXBTNNCS7D
    #     ticker_symbol = ticker
    #
    #     # Global Quote API request
    #     api_request = requests.get(
    #         "https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=" + ticker + "&apikey"
    #                                                                                      "=AD3P4POXBTNNCS7D")
    #     # Overview API request
    #     overview_api_request = requests.get(
    #         "https://www.alphavantage.co/query?function=OVERVIEW&symbol=" + ticker + "&apikey=AD3P4POXBTNNCS7D")
    #
    #
    #     try :
    #         api = json.loads(api_request.content)
    #         overview_api = json.loads(overview_api_request.content)
    #         print("Global Quote API:", api)
    #         print("Overview API:", overview_api)
    #         api_data = api.get('Global Quote', {})
    #         if not api_data :
    #             processed_api = "Error..."
    #         else :
    #             processed_api = {key.replace(' ', '_').replace('.', '') : value for key, value in api_data.items()}
    #     except Exception as e :
    #         print("Exception:", e)
    #         processed_api = "Error..."
    #         overview_api = "Error in Company Overview"
    #
    #     return render(request, 'stockquotes/qhome.html', {'api': processed_api, 'overview': overview_api, 'ticker_symbol': ticker_symbol})
    # else :
    #     return render(request, 'stockquotes/qhome.html', {'ticker' : "Enter a ticker symbol above"})

    # return render(request, 'stockquotes/qhome.html', {'api': processed_api})


@login_required(login_url='login')
def add_stock ( request ) :
    import requests
    import json

    def validate_stock_symbol ( stock_symbol ) :
        api_key = "0BA8N0PMQV2APZGB"
        api_url = f"https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol={stock_symbol}&apikey={api_key}"
        api_request = requests.get(api_url)
        api_data = json.loads(api_request.content).get('Global Quote', {})
        return bool(api_data)

    if request.method == 'POST' :
        form = StockForm (request.POST or None)

        if form.is_valid():
            new_stock = form.save(commit=False)
            new_stock.user = request.user  # Associate this stock with the logged-in user
            stock_symbol = new_stock.ticker

            # Check if the stock symbol already exists in the user's watchlist
            existing_stock = Stock.objects.filter(user=request.user, ticker=stock_symbol).first()

            if existing_stock :
                messages.error(request, "This stock symbol already exists in your watchlist.")
            else:
                is_valid_stock = validate_stock_symbol(stock_symbol)
                if is_valid_stock:
                    new_stock.save()
                    messages.success(request, "Stock Has Been Added!")
                    return redirect('stockquotes:add_stock')
                else:
                    messages.error(request, "Invalid stock symbol. Please try again.")
        else :
            messages.error(request, "There was a problem adding the stock. Please try again.")
        return redirect('stockquotes:add_stock')

    else:
        ticker = Stock.objects.filter(user=request.user)# Filter stocks by the logged-in user
        output = []
        overview_output = []

        for ticker_item in ticker:
            # Global Quote API request
            api_request = requests.get(
                "https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=" + str(ticker_item) + "&apikey=0BA8N0PMQV2APZGB")
            # Overview API request
            overview_api_request = requests.get(
                "https://www.alphavantage.co/query?function=OVERVIEW&symbol=" + str(ticker_item) + "&apikey=0BA8N0PMQV2APZGB")
            try :
                api = json.loads(api_request.content)
                overview_api = json.loads(overview_api_request.content)
                print("Global Quote API:", api)
                print("Overview API:", overview_api)
                api_data = api.get('Global Quote', {})
                if not api_data :
                    processed_api = "Error..."
                else :
                    processed_api = {key.replace(' ', '_').replace('.', '') : value for key, value in api_data.items()}
                    output.append(processed_api)
                    overview_output.append(overview_api)
            except Exception as e :
                print("Exception:", e)
                processed_api = "Error..."
                overview_api = "Error in Company Overview"


            # Zip the two lists together
        output_and_overview = zip(output, overview_output)
        return render(request, 'stockquotes/add_stock.html',
                      {'ticker': ticker, 'output_and_overview': output_and_overview})

def delete(request, stock_id):
    item = Stock.objects.get(pk=stock_id)
    item.delete()
    messages.success(request, ("Stock Has Been Deleted!"))
    return redirect('stockquotes:add_stock')
# Create your views here.

StockMarketSite/stockquotes/templates/stockquotes/add_stock.html
{% extends 'StockMarketApp/base2.html' %}
{% load static %}
{% block content %}

<section class="page-header bg--cover" style="background-image:url({% static 'images/pageheader.png' %})">
    <div class="container">
        <div class="page-header__content" data-aos="fade-right" data-aos-duration="1000">
            <h2>My Watchlist</h2>
            <nav aria-label="breadcrumb" style="--bs-breadcrumb-divider: '/';">
                <ol class="breadcrumb mb-0">
                    <li class="breadcrumb-item "><a href="{% url 'index' %}">Home</a></li>
                    <li aria-current="page" class="breadcrumb-item active">Watchlist</li>
                </ol>
            </nav>
        </div>
        <div class="page-header__shape">
        <span class="page-header__shape-item page-header__shape-item--1">
            <img alt="shape-icon" src="{% static 'images/pageheader2.png' %}"></span>
        </div>
    </div>
</section>



<div class="row mt-5 pt-3">
    <div class="container">
        <form action="{% url 'stockquotes:add_stock'%}" class="d-flex justify-content-center" role="search" method="POST">
            {% csrf_token %}
            <div class="col-lg-7 px-3">
                <input class="form-control me-2" type="search" placeholder="Add Stock to Watchlist" aria-label="Search"
                       name="ticker">
            </div>
            <button class="btn btn-outline-success" type="submit">ADD TICKER</button>
        </form>
    </div>
</div>
<br/>

<section class="blog padding-top padding-bottom of-hidden">
    <div class="container">
<!--        <div class="section-header d-flex align-items-center justify-content-between">-->
<!--            <div class="section-header__content section-header__content&#45;&#45;style3">-->
<!--                <h2 class="mb-0"> Top <span class="style2">Article </span></h2>-->
<!--            </div>-->
<!--        </div>-->
        <div class="blog__wrapper">
            <div data-aos="fade-right" data-aos-duration="1000">
                <table class="table table-hover" >
                    <caption>Stock Watchlist</caption>
                    <thead class="table-dark">
                        <tr>
                            <th scope="col">Symbol</th>
                            <th scope="col">Company</th>
                            <th scope="col">Last Price</th>
                            <th scope="col">Change</th>
                            <th scope="col">%Change</th>
                            <th scope="col">Currency</th>
                            <th scope="col">Volume</th>
                            <th scope="col">Mkt Cap</th>
                        </tr>
                    </thead>
                    <tbody >
                    {% if ticker %}
                        {% for list_item, overview_item in output_and_overview %}
                            <tr>
                                <th scope="row"> {{ list_item.01_symbol }} </th>
                                <td>{{ overview_item.Name }}</td>
                                <td>{{ list_item.05_price }}</td>
                                <td>{{ list_item.09_change }}</td>
                                <td>{{ list_item.10_change_percent }}</td>
                                <td>{{ overview_item.Currency }}</td>
                                <td>{{ list_item.06_volume }}</td>
                                <td>{{ overview_item.MarketCapitalization }}</td>
                            </tr>
                        {% endfor %}
                    {% endif %}

                    </tbody>
                </table>

                <br/><br/>
                {% for item in ticker %}
                    <a href="{% url 'stockquotes:delete' item.id %}" class="btn btn-outline-danger btn-small">Delete {{ item }}</a>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="blog__shape">
        <span class="blog__shape-item blog__shape-item--1"> <span></span> </span>
    </div>
</section>



<style>

.padding-top {
    padding-top: 30px;
}

/* Increase table width */
.table {
    width: 100%;
}

/* Increase padding inside table cells */
.table th, .table td {
    padding: 20px;
    font-size: 16px;  /* Increase font size */
}

/* Optional: Increase table header font size */
.table thead th {
    font-size: 16px;
}
</style>
{% endblock content %}

StockMarketSite/stockquotes/templates/stockquotes/qhome.html
{% extends 'StockMarketApp/base2.html' %}
{% load static %}
{% block content %}

<section class="page-header bg--cover" style="background-image:url({% static 'images/pageheader.png' %})">
    <div class="container">
        <div class="page-header__content" data-aos="fade-right" data-aos-duration="1000">
            <h2>Market Today</h2>
            <nav aria-label="breadcrumb" style="--bs-breadcrumb-divider: '/';">
                <ol class="breadcrumb mb-0">
                    <li class="breadcrumb-item "><a href="{% url 'index' %}">Home</a></li>
                    <li aria-current="page" class="breadcrumb-item active">Quote</li>
                </ol>
            </nav>
        </div>
        <div class="page-header__shape">
        <span class="page-header__shape-item page-header__shape-item--1">
            <img alt="shape-icon" src="{% static 'images/pageheader2.png' %}"></span>
        </div>
    </div>
</section>

<div class="row mt-4 pt-3">
    <div class="container">
        <form action="{% url 'stockquotes:qhome'%}" class="d-flex justify-content-center" role="search" method="POST">
            {% csrf_token %}
            <div class="col-lg-7 px-3">
                <input class="form-control me-2" type="search" placeholder="Get Stock Quote" aria-label="Search"
                       name="ticker">
            </div>
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
    </div>
</div>

<br/>
<br/>

<!-- TradingView Symbol Info Widget BEGIN -->
<div class="container">
    <div class="tradingview-widget-container">
        <div class="tradingview-widget-container__widget"></div>
        <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-symbol-info.js" async>
            {
                "symbol": "{{ ticker_symbol }}",
                "width": "100%",
                "locale": "en",
                "colorTheme": "light",
                "isTransparent": true
            }
        </script>
    </div>
</div>

<br/><br/>
<!-- TradingView Symbol Info Widget END -->

<!-- TradingView Widget BEGIN -->
<div class="tradingview-widget-container">
  <div id="tradingview_221c7"></div>
  <script type="text/javascript" src="https://s3.tradingview.com/tv.js"></script>
  <script type="text/javascript">
  new TradingView.widget(
  {
  "width": "1200",
  "height": "610",
  "symbol": "{{ ticker_symbol }}",
  "interval": "D",
  "timezone": "Asia/Singapore",
  "theme": "dark",
  "style": "1",
  "locale": "en",
  "enable_publishing": false,
  "withdateranges": true,
  "allow_symbol_change": true,
  "details": true,
  "container_id": "tradingview_221c7"
}
  );
  </script>
</div>
<!-- TradingView Widget END -->
<br/><br/>

<section class="service padding-top padding-bottom bg-color-7">
    <div class="section-header section-header--max50">
        <h2 class="mb-15 mt-minus-5"><span class="style2">Company </span>Profile</h2>
        <p>This little widget shows a company description along with key categories - sector & industry.</p>
    </div>
    <div class="container">
        <div class="service__wrapper">
            <div class="row g-4 align-items-center">

                <div class="service__item service__item--style2" data-aos="fade-up" data-aos-duration="800">
                    <!-- TradingView Symbol Profile Widget BEGIN -->
                    <div class="tradingview-widget-container">
                        <div class="tradingview-widget-container__widget"></div>
                        <script async
                                src="https://s3.tradingview.com/external-embedding/embed-widget-symbol-profile.js"
                                type="text/javascript">
                            {
                                "width":"100%",
                                "height":"400",
                                "colorTheme":"light",
                                "isTransparent":false,
                                "symbol":"{{ ticker_symbol }}",
                                "locale": "en"
                            }
                        </script>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="service__shape">
      <span class="service__shape-item service__shape-item--2"> <img src="{% static 'images/footer2.png' %}"
          alt="shape-icon"></span>
      <span class="service__shape-item service__shape-item--3"> <img src="{% static 'images/footer3.png' %}"
          alt="shape-icon">
      </span>
    </div>
</section>


<!-- TradingView Symbol Profile Widget END -->


<!-- TradingView Financial Widget BEGIN -->
<section class="roadmap roadmap--style1 padding-top  padding-bottom bg-color" id="roadmap">
    <div class="container">
        <div class="section-header section-header--max50">
            <h2 class="mb-15 mt-minus-5">Fundamental <span> Data </span></h2>
            <p>Evaluate a company's financial health through key financial ratios, income statements, and balance sheets.</p>
        </div>
        <div class="row gy-4 gy-md-0 gx-5">
            <div class="tradingview-widget-container">
                <div class="tradingview-widget-container__widget"></div>
                <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-financials.js" async>
                    {
                        "colorTheme": "light",
                        "isTransparent": false,
                        "largeChartUrl": "",
                        "displayMode": "regular",
                        "width": "100%",
                        "height": "800",
                        "symbol": "{{ ticker_symbol }}",
                        "locale": "en"
                    }
                </script>
            </div>
        </div>
    </div>

    <div class="roadmap__shape">
<!--      <span class="roadmap__shape-item roadmap__shape-item&#45;&#45;1"> <span></span> </span>-->
      <span class="roadmap__shape-item roadmap__shape-item--2"> <img src="{% static 'images/footer2.png'%}"
                                                                     alt="shape-icon">
      </span>

    </div>

</section>
<!-- TradingView Financial Widget END -->

<!-- TradingView Timeline Widget BEGIN -->
<section class="blog padding-top padding-bottom of-hidden">
    <div class="container">
        <div class="section-header d-flex align-items-center justify-content-between">
            <div class="section-header__content section-header__content--style3">
                <h2 class="mb-0"> Top <span class="style2">Article </span></h2>
            </div>
        </div>
        <div class="blog__wrapper">
            <div data-aos="fade-right" data-aos-duration="1000">
                <div class="tradingview-widget-container">
                    <div class="tradingview-widget-container__widget"></div>
                    <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-timeline.js" async>
                        {
                            "feedMode": "symbol",
                            "symbol": "{{ ticker_symbol }}",
                            "colorTheme": "light",
                            "isTransparent": true,
                            "displayMode": "compact",
                            "width": "100%",
                            "height": "400",
                            "locale": "en"
                        }
                    </script>
                </div>
            </div>
        </div>
    </div>
    <div class="blog__shape">
        <span class="blog__shape-item blog__shape-item--1"> <span></span> </span>
    </div>
</section>
<!-- TradingView Timeline Widget END -->


{% endblock content %}