StockMarketSite/StockMarketApp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('index', views.index, name='index'),
    path('', views.index, name='index'),
    path('prediction',views.prediction, name='prediction'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    #path('home/<str:symbol>/<str:time>', views.suggest, name='suggest')
]

StockMarketSite/StockMarketSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('StockMarketApp.urls')),
    path('stockquotes/', include('stockquotes.urls')),
    path('stocknews/', include('stocknews.urls')),
    path('admin/', admin.site.urls),
]

StockMarketSite/stocknews/urls.py
from django.urls import path
from . import views

app_name = 'stocknews'


urlpatterns = [
    path('news_home/', views.news_home, name="news_home"),
]

StockMarketSite/stockquotes/urls.py
from django.urls import path
from . import views


app_name = 'stockquotes'

urlpatterns = [
    path('qhome/', views.qhome, name="qhome"),
    path('add_stock.html', views.add_stock, name="add_stock"),
    path('delete/<stock_id>', views.delete, name="delete"),
]

StockMarketSite/StockMarketApp/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','password1', 'password2']

StockMarketSite/StockMarketApp/views.py
import numpy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm
# from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.http import HttpResponseRedirect
import requests
import plotly.graph_objects as go
from scipy.interpolate import CubicSpline
from datetime import datetime, timedelta

from numpy import array
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM

import matplotlib.pyplot as plt
import tensorflow as tf
import math


# Create your views here.

def user_login ( request ) :
    page = 'login'
    if request.method == 'POST' :
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None :
            login(request, user)
            return redirect('index')  # Redirect to the home page or dashboard
        else :
            # Invalid login
            return render(request, 'StockMarketApp/login.html', {'error' : 'Invalid username or password','page': page})
    else :
        # Handle GET request
        return render(request, 'StockMarketApp/login.html', {'page': page})


def user_logout ( request ) :
    logout(request)
    return redirect('login')


def user_register ( request ) :
    page = 'register'
    form = CustomUserCreationForm()
    if request.method == 'POST' :
        form = CustomUserCreationForm(request.POST)
        if form.is_valid() :
            user = form.save(commit=False)
            user.save()
            user = authenticate(request, username=user.username, password=request.POST['password1'])

            if user is not None :
                login(request, user)
                messages.success(request, 'Your registration was successful. Welcome!')
                return redirect('index')
        else :
            # Handle form errors here, if needed
            messages.error(request, 'There was a problem with your registration. Please correct the errors below.')

    context = {'form' : form, 'page' : page}
    return render(request, 'StockMarketApp/login.html', context)


def index ( request ) :
    return render(request, "StockMarketApp/index.html", {})


@login_required(login_url='login')
def prediction ( request ) :
    if request.method == 'POST' :
        if 'search' in request.POST :
            stock_name = request.POST.get('stock_search')
            time_frame = request.POST.get('time_frame')

            if not stock_name or not time_frame :
                messages.error(request, 'Symbol or Time frame is empty')
            else :
                plot_div, plot_div2 = call_api(request, time_frame, stock_name)

            return render(request, "StockMarketApp/candlestick_chart.html",
                          {'plot_div' : plot_div, 'plot_div2' : plot_div2})

        else:
            symbol = ''
            time = ''
            if 'AAPL' in request.POST:
                symbol = "AAPL"
                time = '1'
            elif 'TSLA' in request.POST:
                symbol = "TSLA"
                time = '1'
            elif 'SBUX' in request.POST:
                symbol = "SBUX"
                time = '1'
            elif 'META' in request.POST:
                symbol = "META"
                time = '1'
            elif 'NKE' in request.POST:
                symbol = "NKE"
                time = "1"

            plot_div, plot_div2 = call_api(request, time, symbol)

            return render(request, "StockMarketApp/candlestick_chart.html", {'plot_div': plot_div, 'plot_div2':plot_div2 })
    else:
        return render(request, "StockMarketApp/candlestick_chart.html", {})


def call_api(request, time, stock):
    url = ''
    day = ''
    if time == '1':
        day = 'Time Series (Daily)'
        url = 'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=' + stock + '&apikey=0BA8N0PMQV2APZGB'
    elif time == '7':
        day = 'Weekly Adjusted Time Series'
        url = 'https://www.alphavantage.co/query?function=TIME_SERIES_WEEKLY_ADJUSTED&symbol=' + stock + '&apikey=0BA8N0PMQV2APZGB'
    elif time == '30':
        day = 'Monthly Adjusted Time Series'
        url = 'https://www.alphavantage.co/query?function=TIME_SERIES_MONTHLY_ADJUSTED&symbol=' + stock + '&apikey=0BA8N0PMQV2APZGB'
    else:
        messages.error(request, 'Symbol or Time frame is empty')

    if url:
        response = requests.get(url)
        data = response.json()

        if 'Error Message' in data:
            # print('Invalid Stock Symbol')
            messages.error(request, 'Invalid Stock Symbol')
        elif 'Note' in data:
            messages.error(request, 'Thank you for using Alpha Vantage! Our standard API call frequency is 5 calls per minute and 100 calls per day.')
        else:
            dates = []
            open = []
            high = []
            low = []
            close = []

            for date_str, data in data[day].items():
                date_parts = date_str.split("-")

                year = int(date_parts[0])
                month = int(date_parts[1])
                day = int(date_parts[2])

                date = datetime(year, month, day)

                if time != '1':
                    ratio = float(data["5. adjusted close"]) / float(data["4. close"])
                    ratio_adjusted = float(data["1. open"]) / float(data["4. close"])

                    if (ratio * 100) < 80:
                        if ratio_adjusted * 100 > 150:
                            open_price = float(data["5. adjusted close"])
                            high_price = float(data["5. adjusted close"])
                            low_price = float(data["5. adjusted close"])
                        else:
                            open_price = ratio * float(data["1. open"])
                            high_price = ratio * float(data["2. high"])
                            low_price = ratio * float(data["3. low"])

                    else:
                        if (ratio_adjusted * 100) > 150:
                            open_price = float(data["5. adjusted close"])
                            high_price = float(data["5. adjusted close"])
                            low_price = float(data["5. adjusted close"])
                        else:
                            open_price = float(data["1. open"])
                            high_price = float(data["2. high"])
                            low_price = float(data["3. low"])

                    # high_price = float(data["2. high"])
                    # low_price = float(data["3. low"])
                    close_price = float(data["5. adjusted close"])

                    dates.append(date)
                    open.append(open_price)
                    high.append(high_price)
                    low.append(low_price)
                    close.append(close_price)
                else:
                    open_price = float(data["1. open"])
                    high_price = float(data["2. high"])
                    low_price = float(data["3. low"])
                    close_price = float(data["4. close"])

                    dates.append(date)
                    open.append(open_price)
                    high.append(high_price)
                    low.append(low_price)
                    close.append(close_price)

            train, test, prediction = lstm(close, time)

            return chart(open, high, low, close, dates, train, test, prediction, time)


def chart(open, high, low, close, date, train, test, prediction, time):
    # def chart():
    open_data = open
    high_data = high
    low_data = low
    close_data = close
    dates = date

    # print(test)
    # print(prediction)

    train = numpy.array(train)
    train = train.ravel()
    train = ', '.join(map(str, train))
    train = numpy.fromstring(train, sep=',')
    train = train[::-1]

    # print(train)
    print(time)

    test = numpy.array(test)
    test = test.ravel()
    test = ', '.join(map(str, test))
    test = numpy.fromstring(test, sep=',')
    test = test[::-1]

    pred = numpy.array(prediction)
    pred = pred.ravel()
    pred = ', '.join(map(str, pred))
    pred = numpy.fromstring(pred, sep=',')

    test_date = dates[0]

    datess = []

    if time == '1':
        for _ in range(30):
            datess.append(test_date)
            test_date += timedelta(days=1)
    elif time == '7':
        for _ in range(30):
            datess.append(test_date)
            test_date += timedelta(days=7)
    else:
        for _ in range(30):
            datess.append(test_date)
            test_date += timedelta(days=30)

    print(test)
    print(pred)

    # print(dates)

    # Calculate the highest and lowest values in high_data and low_data
    y_max = max(max(high_data), max(low_data))
    y_min = min(min(high_data), min(low_data))

    candle_stick = go.Candlestick(x=dates, open=open_data, high=high_data, low=low_data, close=close_data)

    line = go.Scatter(x=dates, y=close_data, name='Line Chart')

    line_train = go.Scatter(x=dates, y=train, name='Line Chart Train')

    line_test = go.Scatter(x=dates, y=test, name='Line Chart Test')

    line_prediction = go.Scatter(x=datess, y=pred, name='Line Chart Prediction')

    line_fig = go.Figure(data=[line, line_train, line_test, line_prediction])

    fig = go.Figure(data=[candle_stick])

    # Set the y-axis range to fit the data
    fig.update_yaxes(range=[y_min - 1, y_max + 1])  # Add some padding for clarity

    fig.update_layout(xaxis_rangeslider_visible=False, height=600, width=1080, yaxis_autorange=True)

StockMarketSite/StockMarketApp/templates/StockMarketApp/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en" data-bs-theme="dark">
    <head>
        <title>{% block title %}FinStock{% endblock title %}</title>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- Existing CSS and JS links -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet"/>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.0.0/mdb.min.css" rel="stylesheet"/>

        <!-- New CSS and JS links -->
        <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/aos.css' %}">
        <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/swiper-bundle.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>

    <body>
        <!-- ===============>> Preloader start here <<================= -->
        <div class="preloader">
            <img src="{% static 'images/logo.png' %}" alt="preloader icon">
        </div>
        <!-- ===============>> Preloader end here <<================= -->

            <!-- ===============>> light&dark switch start here <<================= -->
        <div class="lightdark-switch d-none">
            <span class="dark-btn" id="btnSwitch">
                <img src="/images/moon.svg" alt="light-dark-switchbtn" class="swtich-icon"/></span>
        </div>
    <!-- ===============>> light&dark switch start here <<================= -->

        <header class="header-section header-section--style1">
            <div class="header-bottom">
                <div class="container">
                    <div class="header-wrapper">
                        <div class="logo">
                            <a href="{% url 'index' %}">
                                <img src="{% static 'images/logo.png' %}" alt="logo">
                            </a>
                        </div>
                        <div class="menu-area">
                            <ul class="menu menu--style1">
                                <li>
                                    <a href="{% url 'index' %}">HOME</a>
                                </li>
                                <li>
                                    <a href="{% url 'prediction' %}">PREDICTION</a>
                                </li>
                                <li>
                                    <a href="{% url 'stocknews:news_home' %}">NEWS</a>
                                </li>
                                <li>
                                    <a href="{% url 'stockquotes:qhome' %}">QUOTES</a>
                                </li>
                                <li>
                                    <a href="{% url 'stockquotes:add_stock' %}">WATCHLIST</a>
                                </li>
                                <li>
                                    {% if request.user.is_authenticated %}
                                        <a href="/">Hello {{request.user}}</a>
                                    {% endif %}
                                </li>
                            </ul>
                        </div>
                        <div class="header-action">
                            <div class="menu-area">
                                <div class="header-btn">
                                    {% if user.is_authenticated %}
                                        <a href="{% url 'logout' %}" class="trk-btn trk-btn--border trk-btn--primary">
                                            <span>Logout</span>
                                        </a>
                                    {% else %}
                                        <a href="{% url 'login' %}" class="trk-btn trk-btn--border trk-btn--primary">
                                            <span>Join Now</span>
                                        </a>
                                    {% endif %}
                                </div>
                                <div class="header-bar d-lg-none header-bar--style1">
                                    <span></span>
                                    <span></span>
                                    <span></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>

        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-warning alert-dismissable" role="alert">
                    <button class="close" data-dismiss="alert">
                        <small><sup>x</sup></small>
                    </button>
                    {{ message }}
                </div><br/>
            {% endfor %}
        {% endif %}
{% block content %}

{% endblock content %}

    <footer class="footer brand-1">
        <div class="container">
            <div class="footer__wrapper">
                <div class="footer__top footer__top--style1">
                    <div class="row gy-5 gx-4">
                        <div class="col-md-6">
                            <div class="footer__about">
                                <a href="{% url 'index' %}" class="footer__about-logo">
                                    <img src="{% static 'images/logo.png' %}" alt="Logo">
                                </a>
                                <p class="footer__about-moto ">Welcome to the Financial Stock Market Information System! This platform aims to provide comprehensive
                                    insights into the stock market, including real-time stock quotes, market analysis, and the latest news.</p>
                            </div>
                        </div>
                        <div class="col-md-2 col-sm-4 col-6">
                            <div class="footer__links">
                                <div class="footer__links-tittle">
                                    <h6>Quick links</h6>
                                </div>
                                <div class="footer__links-content">
                                    <ul class="footer__linklist">
                                        <li class="footer__linklist-item"> <a href="{% url 'index' %}">Home</a></li>
                                        <li class="footer__linklist-item"> <a href="{% url 'stocknews:news_home' %}">News</a></li>
                                        <li class="footer__linklist-item"> <a
                                                href="{% url 'stockquotes:qhome' %}">Quotes
                                        </a></li>
                                        <li class="footer__linklist-item">
                                            <a href="{% url 'prediction' %}">Prediction</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2 col-sm-4">
                            <div class="footer__links">
                                <div class="footer__links-tittle">
                                    <h6>Contact</h6>
                                </div>
                                <div class="footer__links-content">
                                    <ul class="footer__linklist">
                                        <li class="footer__linklist-item"> <a href="#">Asia Pcific University of Technology and
                                        Innovation</a></li>
                                        <li class="footer__linklist-item"> <a href="#">+60192285523</a></li>
                                        <li class="footer__linklist-item"> <a href="#">tp062634@mail.apu.edu.my</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="footer__bottom">
                    <div class="footer__end">
                        <div class="footer__end-copyright">
                            <p class=" mb-0">© 2023 All Rights Reserved By TP062634</p>
                        </div>
                        <div>
                            <ul class="social">
                                <li class="social__item">
                                    <a href="#" class="social__link social__link--style22"><i class="fab fa-facebook-f"></i></a>
                                </li>
                                <li class="social__item">
                                    <a href="#" class="social__link social__link--style22 "><i class="fab fa-instagram"></i></a>
                                </li>
                                <li class="social__item">
                                    <a href="#" class="social__link social__link--style22"><i class="fa-brands fa-linkedin-in"></i></a>
                                </li>
                                <li class="social__item">
                                    <a href="#" class="social__link social__link--style22"><i class="fab fa-youtube"></i></a>
                                </li>
                                <li class="social__item">
                                    <a href="#" class="social__link social__link--style22 "><i class="fab fa-twitter"></i></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer__shape">
            <span class="footer__shape-item footer__shape-item--1"><img src="{% static 'images/footer1.png' %}"
                                                                        alt="shape icon"></span>
            <span class="footer__shape-item footer__shape-item--2"> <span></span> </span>
            <span class="footer__shape-item footer__shape-item--4"><img src="{% static 'images/footer3.png' %}"
                                                                        alt="shape icon"></span>
            <span class="footer__shape-item footer__shape-item--5"><img src="{% static 'images/footer2.png' %}"
                                                                        alt="shape icon"></span>
        </div>
    </footer>
  <!-- ===============>> footer end here <<================= -->

    <!-- ===============>> scrollToTop start here <<================= -->
  <a href="#" class="scrollToTop scrollToTop--home1"><i class="fa-solid fa-arrow-up-from-bracket"></i></a>
  <!-- ===============>> scrollToTop ending here <<================= -->



    <!-- vendor plugins -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"></script>

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/all.min.js' %}"></script>
    <script src="{% static 'js/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'js/aos.js' %}"></script>
    <script src="{% static 'js/fslightbox.js' %}"></script>
    <script src="{% static 'js/purecounter_vanilla.js' %}"></script>

    <script src="{% static 'js/custom.js' %}"></script>
  </body>
</html>

StockMarketSite/StockMarketApp/templates/StockMarketApp/candlestick_chart.html
{% extends 'StockMarketApp/base2.html' %}
{% load static %}
{% block content%}

<section class="page-header bg--cover" style="background-image:url({% static 'images/pageheader.png' %})">
    <div class="container">
        <div class="page-header__content" data-aos="fade-right" data-aos-duration="1000">
            <h2>Prediction Result</h2>
            <nav aria-label="breadcrumb" style="--bs-breadcrumb-divider: '/';">
                <ol class="breadcrumb mb-0">
                    <li class="breadcrumb-item "><a href="{% url 'index' %}">Home</a></li>
                    <li aria-current="page" class="breadcrumb-item active">Prediction</li>
                </ol>
            </nav>
        </div>
        <div class="page-header__shape">
        <span class="page-header__shape-item page-header__shape-item--1">
            <img alt="shape-icon" src="{% static 'images/pageheader2.png' %}"></span>
        </div>
    </div>
</section>


<div class="container">
    <form  method="POST" >
        {% csrf_token %}
        <div class="row mt-5 pt-3">
            <div class="col-lg-7 px-3" >
                <input aria-label="Pick a stock" class="form-control w-100"
                       placeholder="Search symbol to display prediction chart"
                       type="search"
                       name="stock_search" required>
            </div>
            <div class="col-lg-2 pr-3">
                <select class="form-select" aria-label="Time frame" name="time_frame">
                    <option selected>Time frame</option>
                    <option value="1">1 day</option>
                    <option value="7">1 week</option>
                    <option value="30">1 month</option>
                </select>
            </div>
            <div class="col-lg-2">
                <button type="submit" name="search" class="btn btn-outline-success" style="width: 85%" >Search</button>
            </div>
        </div>
    </form>

    <form method="POST">
        {% csrf_token %}
        <div class="row pt-4">
            <div class="col-lg-2 px-2">
<!--                <a href="/home/AAPL/1" class="btn btn-outline-success" role="button" aria-pressed="false">-->
<!--                    AAPL - Apple Inc.-->
<!--                </a>-->
                <button type="submit" name="AAPL" class="btn btn-outline-success" role="button" aria-pressed="false">
                    AAPL - Apple Inc.
                </button>
            </div>
            <div class="col-lg-2 px-2">
<!--                <a href="/home/TSLA/1" class="btn btn-outline-success" role="button" aria-pressed="false">-->
<!--                    TSLA - Tesla Inc.-->
<!--                </a>-->
                <button type="submit" name="TSLA" class="btn btn-outline-success" role="button" aria-pressed="false">
                    TSLA - Tesla Inc.
                </button>
            </div>
            <div class="col-lg-2 px-2">
<!--                <a href="/home/SBUX/1" class="btn btn-outline-success" role="button" aria-pressed="false">-->
<!--                    SBUX - Strbcks.-->
<!--                </a>-->
                <button type="submit" name="SBUX" class="btn btn-outline-success" role="button" aria-pressed="false">
                    SBUX - Strbcks.
                </button>
            </div>
            <div class="col-lg-2 px-2">
<!--                <a href="/home/META/1" class="btn btn-outline-success" role="button" aria-pressed="false">-->
<!--                    META - Meta Inc.-->
<!--                </a>-->
                <button type="submit" name="META" class="btn btn-outline-success" role="button" aria-pressed="false">
                    META - Meta Inc.
                </button>
            </div>
            <div class="col-lg-2 px-2">
<!--                <a href="/home/NKE/1" class="btn btn-outline-success" role="button" aria-pressed="false">-->
<!--                    NKE - Nike Inc.-->
<!--                </a>-->
                <button type="submit" name="NKE" class="btn btn-outline-success" role="button" aria-pressed="false">
                    NKE - Nike Inx.
                </button>
            </div>
        </div>
    </form>
</div><br/><br/><br/>

{% if plot_div %}
    <section class="roadmap roadmap--style1 padding-top  padding-bottom bg-color" id="roadmap">
    <div class="container">
        <div class="section-header section-header--max50">
            <h2 class="mb-15 mt-minus-5">Normal<span> Candlestick Chart </span></h2>
            <p>A normal candlestick chart of the company's stock price</p>
        </div>
        <div class="row gy-4 gy-md-0 gx-5">
            {{ plot_div|safe }}
        </div>
    </div>

    <div class="roadmap__shape">
      <span class="roadmap__shape-item roadmap__shape-item--1"> <span></span> </span>
      <span class="roadmap__shape-item roadmap__shape-item--2"> <img src="{% static 'images/footer2.png'%}"
                                                                     alt="shape-icon">
      </span>

    </div>

</section>

    <section class="feature feature--style2 padding-bottom padding-top feature-bg-color bg--cover"
             style="background-image: url({% static 'images/chartbg.png' %})">
        <div class="section-header section-header--style3 section-header--max57">
            <h2 class="mb-15 mt-minus-5">Prediction Chart</h2>
            <p>The prediction chart below is only for education purpose.
            </p>
        </div>
        <div class="container d-flex justify-content-center align-items-center" style="height: 100%;">
            <div class="feature__wrapper">
                <div class="row g-4 align-items-center">
                    <div class="col-sm-6 col-lg-3">
                        <div class="feature__item" data-aos="fade-up" data-aos-duration="800">

                                {{ plot_div2|safe }}

                        </div>
                    </div>

                </div>
            </div>
        </div>
  </section>
{% endif %}

<!--<div class="row">-->
<!--    <div class="col-lg-6">-->
<!--        {{ plot_div|safe }}-->
<!--    </div>-->
<!--    <div class="col-lg-6">-->
<!--        {{ plot_div2|safe }}-->
<!--    </div>-->
<!--</div>-->

{% if messages %}
<div class="row pt-5">
    <div class="col-lg-2"></div>
    <div class="col-lg-8">
        <div class="alert alert-danger" role="alert">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
    </div>
    <div class="col-lg-2"></div>
</div>
{% endif %}

{% endblock content %}